version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/apps/storybook'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'build: '
    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      digdir:
        patterns:
          - '@digdir/*'
      dependencies-patch-updates:
        update-types:
          - 'patch'
      dependencies-minor-updates:
        update-types:
          - 'minor'
