version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'build: '

    ignore:
      - dependency-name: '@statisticsnorway/design-css'
      - dependency-name: '@statisticsnorway/design-theme'
      - dependency-name: '@statisticsnorway/design-react'

    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
          - 'chromatic'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      digdir:
        patterns:
          - '@digdir/*'
