name: Chromatic

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/storybook/**'
      - 'packages/**'

  push:
    branches:
      - main
    paths:
      - 'apps/storybook/**'
      - 'packages/**'

permissions:
  contents: read

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
