name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Check tool versions
        run: |
          node --version
          npm --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Create or update release pull request
        uses: changesets/action@v2
        with:
          version-script: pnpm changeset:version
          publish-script: pnpm changeset:release
          create-github-releases: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
